version: "3"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  web:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - 8080:8080
    environment:
      - MONGODB_HOST=mongo
